In [ ]:
# pandas - powerful excel



In [5]:
import numpy as np
import pandas as pd

In [6]:
# create a series

# series is very similiar to numpy array
# series is built on top of numpy array

# Logan's visit

# numpy vs series - in series we can have a access label (we can have indiex as labels)
# series can hold any datatypes not only numbers.
# series is a class that exist in pandas

# series has an index number and key associated with it.

In [20]:
label = ['a','b','c']
list = (10,20,30)
arr = np.array([10,20,40])
dict = {'a':10,'b':20,'c':30}

In [23]:
# Converting list into series

pd.Series(list)

print(pd.Series(list))

print(type(pd.Series(list)))

0    10
1    20
2    30
dtype: int64
<class 'pandas.core.series.Series'>


In [22]:
# naming the index

naming_index = pd.Series(list, index=label)
naming_index

a    10
b    20
c    30
dtype: int64

In [ ]:
# converting the array into series

print(pd.Series(arr))

# naming the index 

pd.Series(arr, index=label)

In [28]:
sales_q1_cr = pd.Series([13,145,1134,56], index=['arman financials','prozone realty', 'TCS', 'MGEL'])
sales_q1_cr

arman financials      13
prozone realty       145
TCS                 1134
MGEL                  56
dtype: int64

In [30]:
sales_q2_cr = pd.Series([15,390,1549,14], index=['arman financials','prozone realty', 'TCS', 'LTIM'])
sales_q2_cr

arman financials      15
prozone realty       390
TCS                 1549
LTIM                  14
dtype: int64

In [31]:
sales_q1_cr['arman financials']

13

In [32]:
sales_q2_cr['arman financials']

15

In [34]:

# garbbing the values using index number

sales_q1_cr[0]

/var/folders/j_/x0bf7btx0_l5d3t4jrrlkqjw0000gn/T/ipykernel_8710/610399762.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_q1_cr[0]


13

In [35]:
sales_q2_cr[0]

/var/folders/j_/x0bf7btx0_l5d3t4jrrlkqjw0000gn/T/ipykernel_8710/3619536084.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_q2_cr[0]


15

In [36]:
# operation

sales_q1_cr+sales_q2_cr

LTIM                   NaN
MGEL                   NaN
TCS                 2683.0
arman financials      28.0
prozone realty       535.0
dtype: float64

In [54]:
concat_data = pd.concat([sales_q1_cr , sales_q2_cr])
print(concat_data)
concat_data.keys

arman financials      13
prozone realty       145
TCS                 1134
MGEL                  56
arman financials      15
prozone realty       390
TCS                 1549
LTIM                  14
dtype: int64


<bound method Series.keys of arman financials      13
prozone realty       145
TCS                 1134
MGEL                  56
arman financials      15
prozone realty       390
TCS                 1549
LTIM                  14
dtype: int64>

In [ ]:
# series vs dataframes 

# series -> every values has its own index (unique index)

# datafarmes -> every value shares same index

In [89]:
# randint

print(np.random.randint(10,300,5))
print('\n', np.random.random((100, 40)))
print('linspace \n',np.linspace(100,200,34))
print('randint \n', np.random.randint(-100,300,(5,4)))

[ 18 252 100 277  12]

 [[0.27487495 0.19560429 0.67617749 ... 0.12135183 0.53809424 0.21918235]
 [0.0524473  0.09994763 0.99839079 ... 0.37781397 0.90198692 0.16660623]
 [0.94852818 0.9601329  0.83842511 ... 0.93636695 0.75883595 0.72745769]
 ...
 [0.28967343 0.5921904  0.43329656 ... 0.2987514  0.1787929  0.50144922]
 [0.74010523 0.51978958 0.41228185 ... 0.22616898 0.77804571 0.14085777]
 [0.50079452 0.15827235 0.7913175  ... 0.08670458 0.98689336 0.23990625]]
linspace 
 [100.         103.03030303 106.06060606 109.09090909 112.12121212
 115.15151515 118.18181818 121.21212121 124.24242424 127.27272727
 130.3030303  133.33333333 136.36363636 139.39393939 142.42424242
 145.45454545 148.48484848 151.51515152 154.54545455 157.57575758
 160.60606061 163.63636364 166.66666667 169.6969697  172.72727273
 175.75757576 178.78787879 181.81818182 184.84848485 187.87878788
 190.90909091 193.93939394 196.96969697 200.        ]
randint 
 [[ 105   13 -100   85]
 [ -18   13 -100  157]
 [  35  -31  -5

In [7]:

# random seed is going to give the same values, rather than changing the values randomly (unlike random.randint)


np.random.seed(42)
data = np.random.randint(-100,100,(5,4))
data

array([[  2,  79,  -8, -86],
       [  6, -29,  88, -80],
       [  2,  21, -26, -13],
       [ 16,  -1,   3,  51],
       [ 30,  49, -48, -99]])

In [8]:
index = ['A','B','C','D','E']
columns = ['x','y','w','z']
df = pd.DataFrame(data, index, columns)
df

x   y   w   z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [9]:
# selection and indexing

df['w']

A    -8
B    88
C   -26
D     3
E   -48
Name: w, dtype: int64

In [132]:
df['x']

A     2
B     6
C     2
D    16
E    30
Name: x, dtype: int64

In [133]:
type(df['x'])

# every column is a dataframe

pandas.core.series.Series

In [134]:
type(df)

pandas.core.frame.DataFrame

In [ ]:

# data frame is a collection of series

# series can hold any datatypes not only numbers.
# series is a class that exist in pandas

# series has an index number and key associated with it.


In [141]:
test = df[['w','z']]
test

w   z
A  -8 -86
B  88 -80
C -26 -13
D   3  51
E -48 -99

In [148]:

# adding a new column

df['sum_of_x_and_y'] = df['x'] + df['y']
df

df['prod_of_x_and_y'] = df['x'] * df['y']
df

x   y   w   z  sum_of_x_and_y  prod_of_x_and_y
A   2  79  -8 -86              81              158
B   6 -29  88 -80             -23             -174
C   2  21 -26 -13              23               42
D  16  -1   3  51              15              -16
E  30  49 -48 -99              79             1470

In [152]:
# dropping the column

# axis - 0 -> row / index
# axis - 1 -> column

df.drop('prod_of_x_and_y', axis=1)

# but the drop won't reflect in the main data frame

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
B   6 -29  88 -80             -23
C   2  21 -26 -13              23
D  16  -1   3  51              15
E  30  49 -48 -99              79

In [153]:
df

x   y   w   z  sum_of_x_and_y  prod_of_x_and_y
A   2  79  -8 -86              81              158
B   6 -29  88 -80             -23             -174
C   2  21 -26 -13              23               42
D  16  -1   3  51              15              -16
E  30  49 -48 -99              79             1470

In [157]:
# inorder to make the drop permenantly happen / reflect in the dataframe, 
# we need to use inplace

df.drop('prod_of_x_and_y', axis=1, inplace=True)


In [159]:

# now the drop is relected

df

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
B   6 -29  88 -80             -23
C   2  21 -26 -13              23
D  16  -1   3  51              15
E  30  49 -48 -99              79

In [160]:
df.drop('E',axis=0)

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
B   6 -29  88 -80             -23
C   2  21 -26 -13              23
D  16  -1   3  51              15

In [163]:
# working with rows

df['A']



KeyError: 'A'

In [164]:
# in order to grab row, we need to use loc

df.loc['A']

x                  2
y                 79
w                 -8
z                -86
sum_of_x_and_y    81
Name: A, dtype: int64

In [165]:
df.loc['B']

x                  6
y                -29
w                 88
z                -80
sum_of_x_and_y   -23
Name: B, dtype: int64

In [166]:
type(df.loc['B'])

pandas.core.series.Series

In [168]:
# grabbing the row using the index value

df.iloc[1]

x                  6
y                -29
w                 88
z                -80
sum_of_x_and_y   -23
Name: B, dtype: int64

In [169]:
df.iloc[0:2]

x   y   w   z  sum_of_x_and_y
A  2  79  -8 -86              81
B  6 -29  88 -80             -23

In [170]:
df

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
B   6 -29  88 -80             -23
C   2  21 -26 -13              23
D  16  -1   3  51              15
E  30  49 -48 -99              79

In [174]:
# grabbing the subset of a dataframe (2,-8, 2 and -26)

# step 1 :  grab the row
df.loc[['A','C']]

x   y   w   z  sum_of_x_and_y
A  2  79  -8 -86              81
C  2  21 -26 -13              23

In [175]:
# step 2: grab the column

df.loc[['A','C'], ['x','w']]

x   w
A  2  -8
C  2 -26

In [178]:
# grabbing - 29, 80 and -1 and 51

# step 1 : 

df.loc[['B','D']]



x   y   w   z  sum_of_x_and_y
B   6 -29  88 -80             -23
D  16  -1   3  51              15

In [179]:
# step 2 : 

df.loc[['B','D'],['y','z']]

y   z
B -29 -80
D  -1  51

In [180]:
# conditional selection

df

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
B   6 -29  88 -80             -23
C   2  21 -26 -13              23
D  16  -1   3  51              15
E  30  49 -48 -99              79

In [184]:
df > 0

x      y      w      z  sum_of_x_and_y
A  True   True  False  False            True
B  True  False   True  False           False
C  True   True  False  False            True
D  True  False   True   True            True
E  True   True  False  False            True

In [183]:
df

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
B   6 -29  88 -80             -23
C   2  21 -26 -13              23
D  16  -1   3  51              15
E  30  49 -48 -99              79

In [185]:
df[df>0]

x     y     w     z  sum_of_x_and_y
A   2  79.0   NaN   NaN            81.0
B   6   NaN  88.0   NaN             NaN
C   2  21.0   NaN   NaN            23.0
D  16   NaN   3.0  51.0            15.0
E  30  49.0   NaN   NaN            79.0

In [186]:
# on a particular column

df['x']>0

A    True
B    True
C    True
D    True
E    True
Name: x, dtype: bool

In [187]:
df[df['y']>0]

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
C   2  21 -26 -13              23
E  30  49 -48 -99              79

In [190]:
df

x   y   w   z  sum_of_x_and_y
A   2  79  -8 -86              81
B   6 -29  88 -80             -23
C   2  21 -26 -13              23
D  16  -1   3  51              15
E  30  49 -48 -99              79

In [189]:
# grabbing the value of z based on the value of y

df[df['y']>0]['z']

A   -86
C   -13
E   -99
Name: z, dtype: int64

In [191]:
df[df['y']>0][['w','z']]

w   z
A  -8 -86
C -26 -13
E -48 -99

In [12]:
df[(df['w']>0) & (df['w']>5)]

x   y   w   z
B  6 -29  88 -80

In [13]:
df

x   y   w   z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [14]:
# reset index

df.reset_index()

index   x   y   w   z
0     A   2  79  -8 -86
1     B   6 -29  88 -80
2     C   2  21 -26 -13
3     D  16  -1   3  51
4     E  30  49 -48 -99

In [20]:
df

x   y   w   z
A   2  79  -8 -86
B   6 -29  88 -80
C   2  21 -26 -13
D  16  -1   3  51
E  30  49 -48 -99

In [19]:
df.reset_index()

index   x   y   w   z
0     A   2  79  -8 -86
1     B   6 -29  88 -80
2     C   2  21 -26 -13
3     D  16  -1   3  51
4     E  30  49 -48 -99

In [24]:
new_index = ['JK','DH','BL','AP','TN']

In [25]:
# to rename the index, first create a new column


# create a new column


df['new_column'] = new_index

In [26]:
df

x   y   w   z new_column
A   2  79  -8 -86         JK
B   6 -29  88 -80         DH
C   2  21 -26 -13         BL
D  16  -1   3  51         AP
E  30  49 -48 -99         TN

In [27]:
# changing the new_column as new index 

df.set_index('new_column')

x   y   w   z
new_column                
JK           2  79  -8 -86
DH           6 -29  88 -80
BL           2  21 -26 -13
AP          16  -1   3  51
TN          30  49 -48 -99

In [28]:
df


x   y   w   z new_column
A   2  79  -8 -86         JK
B   6 -29  88 -80         DH
C   2  21 -26 -13         BL
D  16  -1   3  51         AP
E  30  49 -48 -99         TN

In [29]:
# in order to make it permanant

df = df.set_index('new_column')

In [30]:
df

x   y   w   z
new_column                
JK           2  79  -8 -86
DH           6 -29  88 -80
BL           2  21 -26 -13
AP          16  -1   3  51
TN          30  49 -48 -99

In [32]:
df.loc['DH']
df.loc['TN']

x    30
y    49
w   -48
z   -99
Name: TN, dtype: int64

In [41]:
newIn = ['India','India','Germany','India','Brazil']
df['newIn'] = newIn
df.set_index('newIn')

x   y   w   z
newIn                  
India     2  79  -8 -86
India     6 -29  88 -80
Germany   2  21 -26 -13
India    16  -1   3  51
Brazil   30  49 -48 -99

In [62]:
df
print(df.columns)
df.describe()

Index(['x', 'y', 'w', 'z'], dtype='object')


x          y          w          z
count   5.00000   5.000000   5.000000   5.000000
mean   11.20000  23.800000   1.800000 -45.400000
std    11.96662  42.109381  51.915316  63.366395
min     2.00000 -29.000000 -48.000000 -99.000000
25%     2.00000  -1.000000 -26.000000 -86.000000
50%     6.00000  21.000000  -8.000000 -80.000000
75%    16.00000  49.000000   3.000000 -13.000000
max    30.00000  79.000000  88.000000  51.000000

In [46]:
# df = df.set_index('newIn')
df.reset_index()

newIn   x   y   w   z
0    India   2  79  -8 -86
1    India   6 -29  88 -80
2  Germany   2  21 -26 -13
3    India  16  -1   3  51
4   Brazil  30  49 -48 -99

In [47]:
change = ['Try','Try','Change','Adapt','Evolve']
change

['Try', 'Try', 'Change', 'Adapt', 'Evolve']

In [48]:
df['new'] = change

In [49]:
df

x   y   w   z     new
newIn                          
India     2  79  -8 -86     Try
India     6 -29  88 -80     Try
Germany   2  21 -26 -13  Change
India    16  -1   3  51   Adapt
Brazil   30  49 -48 -99  Evolve

In [50]:
df.set_index('new')

x   y   w   z
new                   
Try      2  79  -8 -86
Try      6 -29  88 -80
Change   2  21 -26 -13
Adapt   16  -1   3  51
Evolve  30  49 -48 -99

In [51]:
df

x   y   w   z     new
newIn                          
India     2  79  -8 -86     Try
India     6 -29  88 -80     Try
Germany   2  21 -26 -13  Change
India    16  -1   3  51   Adapt
Brazil   30  49 -48 -99  Evolve

In [52]:
df=df.set_index('new')

In [53]:
df

x   y   w   z
new                   
Try      2  79  -8 -86
Try      6 -29  88 -80
Change   2  21 -26 -13
Adapt   16  -1   3  51
Evolve  30  49 -48 -99

In [57]:
df.loc['Try']

x   y   w   z
new               
Try  2  79  -8 -86
Try  6 -29  88 -80

In [ ]:
 # every column and every row is a series in dataframes

In [58]:
df.describe()

x          y          w          z
count   5.00000   5.000000   5.000000   5.000000
mean   11.20000  23.800000   1.800000 -45.400000
std    11.96662  42.109381  51.915316  63.366395
min     2.00000 -29.000000 -48.000000 -99.000000
25%     2.00000  -1.000000 -26.000000 -86.000000
50%     6.00000  21.000000  -8.000000 -80.000000
75%    16.00000  49.000000   3.000000 -13.000000
max    30.00000  79.000000  88.000000  51.000000

In [59]:
df.dtypes

x    int64
y    int64
w    int64
z    int64
dtype: object

In [60]:
df

x   y   w   z
new                   
Try      2  79  -8 -86
Try      6 -29  88 -80
Change   2  21 -26 -13
Adapt   16  -1   3  51
Evolve  30  49 -48 -99

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Try to Evolve
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       5 non-null      int64
 1   y       5 non-null      int64
 2   w       5 non-null      int64
 3   z       5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes
