In [1]:


# vector often represents n independent measurements of same quantitative property

# ex - heights of n different employees, income of n different employees, heart rate of n different patients etc.

In [ ]:
# we will be dealing with n points in m dimensional space

In [2]:
# n x m
# n -> rows
# m -> columns

# vectors and matrices where designed to store the data of same type

In [4]:
import numpy as np
body = np.genfromtxt("https://raw.githubusercontent.com/gagolews/" + "teaching-data/master/marek/nhanes_adult_female_bmx_2020.csv", delimiter=",")

In [6]:
body

array([[  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 97.1, 160.2,  34.7, ...,  35.8, 126.1, 117.9],
       [ 91.1, 152.7,  33.5, ...,  38.5, 125.5, 103.1],
       ...,
       [ 73. , 159.6,  36.2, ...,  31.4, 104.6,  99.3],
       [ 78.6, 168.5,  38.1, ...,  36. , 102.4,  98.5],
       [ 82.8, 147.8,  34.8, ...,  39.5, 121.4, 110. ]])

In [24]:
body = np.genfromtxt("https://raw.githubusercontent.com/gagolews/" + 
                     "teaching-data/master/marek/nhanes_adult_female_bmx_2020.csv", delimiter=",")[1:, :] # skip first row (column names)

In [25]:
body

array([[ 97.1, 160.2,  34.7, ...,  35.8, 126.1, 117.9],
       [ 91.1, 152.7,  33.5, ...,  38.5, 125.5, 103.1],
       [ 73. , 161.2,  37.4, ...,  31.8, 106.2,  92. ],
       ...,
       [ 73. , 159.6,  36.2, ...,  31.4, 104.6,  99.3],
       [ 78.6, 168.5,  38.1, ...,  36. , 102.4,  98.5],
       [ 82.8, 147.8,  34.8, ...,  39.5, 121.4, 110. ]])

In [26]:
body[:6, :] # first 6 rows and all columns

array([[ 97.1, 160.2,  34.7,  40.8,  35.8, 126.1, 117.9],
       [ 91.1, 152.7,  33.5,  33. ,  38.5, 125.5, 103.1],
       [ 73. , 161.2,  37.4,  38. ,  31.8, 106.2,  92. ],
       [ 61.7, 157.4,  38. ,  34.7,  29. , 101. ,  90.5],
       [ 55.4, 154.6,  34.6,  34. ,  28.3,  92.5,  73.2],
       [ 62. , 144.7,  32.5,  34.2,  29.8, 106.7,  84.8]])

In [27]:
body_columns = np.array([
    "weight (kg)",
    "standing height (cm)",
    "upper arm len. (cm)",
    "upper leg len. (cm)",
    "arm circ. (cm)",
    "hip circ. (cm)",
    "waist circ. (cm)"
])

In [28]:
body_columns

array(['weight (kg)', 'standing height (cm)', 'upper arm len. (cm)',
       'upper leg len. (cm)', 'arm circ. (cm)', 'hip circ. (cm)',
       'waist circ. (cm)'], dtype='<U20')

In [29]:
type(body)

numpy.ndarray

In [30]:
body.ndim

2

In [31]:
body.shape

(4221, 7)

In [33]:
np.array([[1,2,4,5],[2,4,5,6],[3,4,5,7]])

array([[1, 2, 4, 5],
       [2, 4, 5, 6],
       [3, 4, 5, 7]])

In [42]:
# uni dimensional 
np.array([1,2,3,4])

# multi dimensional 3 x 1
print("\n",np.array([[1],[2],[3]]))

# multi dimensional 1 x 3
np.array([[1,2,3,]])


 [[1]
 [2]
 [3]]


array([[1, 2, 3]])

In [59]:

# column vector -> a single column of numbers / observations

print("column vector \n",np.array([[1],[2],[3],[4]]))

column vector 
 [[1]
 [2]
 [3]
 [4]]


In [70]:

# row vector -> a single row of numbers / observations

print("row vector \n",np.array([[1,2,3,4]]))

row vector 
 [[1 2 3 4]]


In [75]:

# repeating arrays 

# repeats a row vector -> row wisely

np.repeat([[1,2,3,4]],3, axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [77]:

# repeats a column vector -> column wisely

np.repeat([[1],[2],[3],[4]],3,axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [98]:

# Excercises


np.repeat([[1,2],[3,4]],[2,3],axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [100]:
np.repeat([[1,2]],3,axis=1)

array([[1, 1, 1, 2, 2, 2]])

In [108]:
np.repeat([[1,2,3],[4,5,6]],[2,4],axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [111]:
np.column_stack(([10,20],[40,50],[90,100]))

array([[ 10,  40,  90],
       [ 20,  50, 100]])

In [112]:
np.row_stack(([10,20],[40,50],[90,100]))

array([[ 10,  20],
       [ 40,  50],
       [ 90, 100]])

In [135]:
arr1 = [1,2,3]
arr2 = [4,5,6]
_2darr1 = np.expand_dims(arr1,axis=1)
_2darr2 = np.expand_dims(arr2,axis=1)
print(_2darr1)
print(_2darr2)
_2dr_arr1 = np.expand_dims(arr1,axis=0)
_2dc_arr1 = np.expand_dims(arr2,axis=0)
print(_2dr_arr1)
print(_2dc_arr2)
np.append(_2dr_arr1,_2dc_arr1)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
[[1 2 3]]
[[4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [160]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
np.concatenate((arr1,arr2.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [159]:
arr1

array([[1, 2],
       [3, 4]])

In [163]:
arr1 = [1,2,3]
arr2 = [4,5,6]
np.c_[arr1,arr2] 
#np.c_ for second axis / axis = 1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [164]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Stack arr2 vertically on top of arr1
stacked_arr = np.vstack((arr1, arr2))
print("Vertically stacked array:", stacked_arr)

Vertically stacked array: [[1 2]
 [3 4]
 [5 6]]


In [167]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

# Stack arr2 horizontally to the right of arr1
stacked_arr = np.hstack((arr1, arr2))
print("Horizontally stacked array:", stacked_arr)

Horizontally stacked array: [[1 2 5]
 [3 4 6]]


In [178]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
original_array
new_array = np.array([[10,20,30]])

# adding new row at the beginning

np.insert(original_array,0,new_array,axis=0)

# adding new row at the end

np.insert(original_array,len(original_array),new_array,axis=0)

# adding new array in the middle

np.insert(original_array,2,new_array,axis=0)

# same for column -> just need to change as axis = 1

np.insert(original_array,len(original_array),new_array,axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [240]:
np.random.seed(123)
np.random.rand(2, 5)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
       [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752]])

In [242]:
import scipy as scipy
scipy.stats.uniform.rvs(0, 1, size=(2, 5), random_state=123)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
       [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752]])

In [248]:
A = np.array([
[1, 2, 3, 4], [5, 6, 7, 8], [ 9, 10, 11, 12 ]
])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [244]:
A.argmax()

11

In [245]:
A.size

12

In [246]:
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [249]:
A.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [250]:
A.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [253]:
np.linspace(0, 1, 5).reshape(1,-1)

array([[0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [254]:
np.array([9099, 2537, 1832]).reshape(-1, 1)

array([[9099],
       [2537],
       [1832]])

In [255]:
np.arange(24).reshape(2, 4, 3)

# depth = 2
# 4 = rows
# 3 = columns

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])